import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import React,{useState} from 'react';
import { ActivityIndicator,Alert,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View } from 'react-native';
import { useUser } from '@/providers/user-provider';
import { colors } from '@/shared/theme/colors';

type TipoUsuario='AGENTE'|'CONTRATANTE';
export default function RegisterScreen(){
 const navigation=useNavigation<any>(); const {updateProfile}=useUser();
 const [tipoUsuario,setTipoUsuario]=useState<TipoUsuario>('AGENTE'); const [nome,setNome]=useState(''); const [email,setEmail]=useState(''); const [senha,setSenha]=useState('');
 const [empresa,setEmpresa]=useState(''); const [telefone,setTelefone]=useState(''); const [categoria,setCategoria]=useState(''); const [cidade,setCidade]=useState(''); const [endereco,setEndereco]=useState(''); const [site,setSite]=useState(''); const [descricao,setDescricao]=useState(''); const [especialidade,setEspecialidade]=useState(''); const [carregando,setCarregando]=useState(false);
 const handleRegister=async()=>{if(!nome.trim()||!email.trim()||!senha.trim()){Alert.alert('Atenção','Preencha nome, e-mail e senha.');return;}if(tipoUsuario==='CONTRATANTE'&&!empresa.trim()){Alert.alert('Atenção','Informe o nome da empresa ou organização.');return;}setCarregando(true);try{updateProfile({nome,email,tipo:tipoUsuario,empresa,telefone,categoria,cidade,endereco,site,descricao,especialidade});navigation.navigate(tipoUsuario==='AGENTE'?'CreatePortfolio':'CustomizeProfile');}catch(e){Alert.alert('Não foi possível cadastrar',e instanceof Error?e.message:'Tente novamente.');}finally{setCarregando(false);}};
 return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.title}>Criar conta</Text><Text style={styles.subtitle}>Monte seu perfil para conectar pessoas e oportunidades na economia criativa.</Text>
 <Text style={styles.section}>Tipo de perfil</Text><View style={styles.roles}><TouchableOpacity style={[styles.role,tipoUsuario==='AGENTE'&&styles.roleActive]} onPress={()=>setTipoUsuario('AGENTE')}><Ionicons name="color-palette-outline" size={25} color={tipoUsuario==='AGENTE'?colors.primaryDark:colors.muted}/><Text style={styles.roleTitle}>Agente Criativo</Text><Text style={styles.roleSub}>Artista ou profissional</Text></TouchableOpacity><TouchableOpacity style={[styles.role,tipoUsuario==='CONTRATANTE'&&styles.roleActive]} onPress={()=>setTipoUsuario('CONTRATANTE')}><Ionicons name="briefcase-outline" size={25} color={tipoUsuario==='CONTRATANTE'?colors.primaryDark:colors.muted}/><Text style={styles.roleTitle}>Contratante</Text><Text style={styles.roleSub}>Empresa ou organização</Text></TouchableOpacity></View>
 <Text style={styles.section}>Dados de acesso</Text><Field icon="person-outline" placeholder="Nome completo / responsável" value={nome} onChangeText={setNome}/><Field icon="mail-outline" placeholder="E-mail" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none"/><Field icon="lock-closed-outline" placeholder="Senha" value={senha} onChangeText={setSenha} secureTextEntry/>
 {tipoUsuario==='CONTRATANTE'?<><Text style={styles.section}>Dados da organização</Text><Field icon="business-outline" placeholder="Empresa / organização *" value={empresa} onChangeText={setEmpresa}/><Field icon="pricetag-outline" placeholder="Categoria de atuação" value={categoria} onChangeText={setCategoria}/><Field icon="call-outline" placeholder="Telefone" value={telefone} onChangeText={setTelefone} keyboardType="phone-pad"/><Field icon="location-outline" placeholder="Cidade" value={cidade} onChangeText={setCidade}/><Field icon="navigate-outline" placeholder="Endereço" value={endereco} onChangeText={setEndereco}/><Field icon="globe-outline" placeholder="Site ou rede social" value={site} onChangeText={setSite}/><TextInput style={styles.textarea} placeholder="Descreva a empresa, eventos e serviços..." placeholderTextColor={colors.muted} value={descricao} onChangeText={setDescricao} multiline maxLength={500}/></>:<><Text style={styles.section}>Perfil profissional</Text><Field icon="sparkles-outline" placeholder="Especialidade" value={especialidade} onChangeText={setEspecialidade}/><Field icon="location-outline" placeholder="Cidade" value={cidade} onChangeText={setCidade}/></>}
 <TouchableOpacity style={styles.button} onPress={handleRegister} disabled={carregando}>{carregando?<ActivityIndicator color={colors.white}/>:<Text style={styles.buttonText}>{tipoUsuario==='AGENTE'?'Continuar para portfólio':'Personalizar perfil'}</Text>}</TouchableOpacity><TouchableOpacity onPress={()=>navigation.goBack()} style={styles.login}><Text style={styles.loginText}>Já possui uma conta? <Text style={styles.bold}>Faça login</Text></Text></TouchableOpacity>
 </ScrollView></SafeAreaView>;
}
function Field({icon,...props}:{icon:keyof typeof Ionicons.glyphMap}&React.ComponentProps<typeof TextInput>){return <View style={styles.inputWrap}><Ionicons name={icon} size={19} color={colors.muted}/><TextInput style={styles.input} placeholderTextColor={colors.muted} {...props}/></View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},content:{padding:22,paddingBottom:40},title:{fontSize:32,fontWeight:'900',color:colors.primaryDark,textAlign:'center'},subtitle:{fontSize:14,lineHeight:20,color:colors.muted,textAlign:'center',marginTop:5,marginBottom:22},section:{fontSize:14,fontWeight:'900',color:colors.text,marginTop:12,marginBottom:10},roles:{flexDirection:'row',gap:10,marginBottom:8},role:{flex:1,backgroundColor:colors.white,borderWidth:1.5,borderColor:colors.border,borderRadius:15,padding:14,alignItems:'center'},roleActive:{borderColor:colors.primaryDark,backgroundColor:colors.surfaceStrong},roleTitle:{fontSize:13,fontWeight:'900',color:colors.text,marginTop:6},roleSub:{fontSize:10,color:colors.muted,marginTop:2},inputWrap:{height:50,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:10,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:9,marginBottom:11},input:{flex:1,color:colors.text,fontSize:14},textarea:{minHeight:105,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:10,padding:13,color:colors.text,fontSize:14,textAlignVertical:'top',marginBottom:11},button:{height:52,borderRadius:11,backgroundColor:colors.primaryDark,alignItems:'center',justifyContent:'center',marginTop:12},buttonText:{color:colors.white,fontSize:15,fontWeight:'900'},login:{alignItems:'center',marginTop:19},loginText:{color:colors.muted,fontSize:13},bold:{color:colors.primaryDark,fontWeight:'900'}});
